IOP kernel DeleteEventFlag test
unknownbrackets/ps2autotests pull request #46
Opened 2016-12-29 02:56 UTC by jpd002

Basic test for DeleteEventFlag kernel function.

2016-12-29 03:01 UTC, jpd002 commented
Also, since you've given me "Collaborator" rights, how should we proceed if I want to submit changes to this repo? Do you still want me to use pull requests?

2016-12-29 19:19 UTC, unknownbrackets requested changes
Well, I think it's still best to review, but figured you should have access.

-[Unknown]

2016-12-29 19:19 UTC, unknownbrackets commented on tests/kernel/iop/eventflag/delete.expected
> +  DeleteThread returned: 0
For illustration, what about deleting twice?

-[Unknown]

2016-12-30 03:43 UTC, jpd002 commented on tests/kernel/iop/eventflag/delete.expected
> +  DeleteThread returned: 0
I've pushed a commit that adds that test case.

2016-12-30 03:50 UTC, unknownbrackets commented on tests/kernel/iop/eventflag/delete.expected
> +  DeleteThread returned: 0
Thanks.

-[Unknown]

2016-12-30 03:50 UTC, merged

2016-12-30 03:52 UTC, jpd002 commented
Thanks for merging!